name: Lazatek
favicon: null
layout_spectrum: 0.51222
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ec1c25'
    - '#eeeeee'
    - '#757273'
    - '#b3b1b2'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
